import Head from "next/head";
import Image from "next/image";
import GlobalStyle from "../styles/globals";
import Landing from "./landing";

export default function Home() {
  return (
    <div>
      <GlobalStyle />
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Landing />
      </main>

      {/* <footer></footer> */}
    </div>
  );
}
