import Head from "next/head";

export default function Landing() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Golden Screen</h1>
      </main>

      {/* <footer></footer> */}
    </div>
  );
}
